{"blogid": "126743551", "writerAge": "码龄2年", "writerBlogNum": "461", "writerCollect": "805", "writerComment": "40", "writerFan": "19145", "writerGrade": "6级", "writerIntegral": "5156", "writerName": "繁华哟", "writerProfileAdress": "writer_image\\profile_126743551.jpg", "writerRankTotal": "3196", "writerRankWeekly": "346", "writerThumb": "123", "writerVisitNum": "320558", "blog_read_count": "9", "blog_time": "于 2022-09-07 13:08:21 发布", "blog_title": "Jvm中的内存溢出和内存泄露", "content": "<div class=\"article_content clearfix\" id=\"article_content\">\n<link href=\"style.css\" rel=\"stylesheet\"/>\n<div class=\"markdown_views prism-atom-one-dark\" id=\"content_views\">\n<svg style=\"display: none;\" xmlns=\"http://www.w3.org/2000/svg\">\n<path d=\"M5,0 0,2.5 5,5z\" id=\"raphael-marker-block\" stroke-linecap=\"round\" style=\"-webkit-tap-highlight-color: rgba(0, 0, 0, 0);\"></path>\n</svg>\n<p><strong>1.System.gc()的理解</strong></p>\n<p><img alt=\"\" src=\"image\\d54e656da68c4c0fb45b4e22f25283dd.png\"/></p>\n<p>当try-catch-finally的时候，当在finally中的要执行的代码前，出现了System.gc(),那么finally里面是不会执行的</p>\n<p><strong>2.内存溢出(OOM)</strong></p>\n<p><img alt=\"\" src=\"image\\8c6f3f1c17ae4011be6b371674446acf.png\"/></p>\n<p><img alt=\"\" src=\"image\\2ed26cb84e854d25a337df6619db8274.png\"/></p>\n<p><strong>3.内存泄露</strong></p>\n<p><img alt=\"\" src=\"image\\349f89b8b29943ccbaee90a827888a7f.png\"/></p>\n<p><img alt=\"\" src=\"image\\a1e052ff208c4662a8635024f0a7bca0.png\"/></p>\n</div>\n<link href=\"https://csdnimg.cn/release/blogv2/dist/mdeditor/css/editerView/markdown_views-22a2fefd3b.css\" rel=\"stylesheet\"/>\n<link href=\"https://csdnimg.cn/release/blogv2/dist/mdeditor/css/style-4f8fbf9108.css\" rel=\"stylesheet\"/>\n</div>"}